name       : python-whatthepatch
version    : 1.0.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/w/whatthepatch/whatthepatch-1.0.2.tar.gz : c540ea59173e0a291e19c742dd8b406c56e2be039a600edb7c6fc3ae4bbdfa9f
homepage   : https://github.com/cscorley/whatthepatch
license    : MIT
component  : programming.python
summary    : A patch parsing and application library.
description: |
    What The Patch!? is a library for both parsing and applying patch files.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
