name       : python-whatthepatch
version    : 1.0.5
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/w/whatthepatch/whatthepatch-1.0.5.tar.gz : 7f374c172812581bc3763587525d14a143aac7fe4220bc4676ecce0d86cb8f08
homepage   : https://github.com/cscorley/whatthepatch
license    : MIT
component  : programming.python
summary    : A patch parsing and application library
description: |
    What The Patch!? is a library for both parsing and applying patch files.
builddeps  :
    - python-build
    - python-installer
    - python-pytest
    - python-wheel
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
